### ISSUE TITLE
Why use D32/D64 environment variables instead of target_pointer_width directive?

### ISSUE THREAD

**Issue by vimmerru** [milagro-crypto/amcl#61]
Hi,

@mcarrickscott  I noticed that you changed target_pointer_width directive to D32/D64 environment variable in commit a136cd4b2f86ce7a77672920bae34968605409a8?

What is the reason for this change? "target_pointer_width" is native Rust directive that allows to determine pointer size on compile time in rust. On previous commit there was consistent build for all platforms without necessity to involve any custom configuration. Now we need to have custom build for all supported platforms.

**Comment by mcarrickscott** [comment]
I didn't know that  "target_pointer_width" was a native Rust directive. Not
everybody does..

Anyway I have now fixed it.

A question for you..

If I use rustup to provide support for a 32-bit target,
like i686-unknown-linux-gnu, how can I easily switch between targets. The
point being for the non-rust expert who simply wants to follow the readme
instructions in order to see support demonstrated for a 32-bit target?

Mike

**Comment by KitHat** [comment]
I think this fix will make both variants possible to use: #62

**Comment by mcarrickscott** [comment]
Actually you guys have convinced me that D32/D64 is a bad idea.

I can test a 32-bit build here using wasm32-unknown-emscripten

So lets leave it as it is..

Mike

**Comment by vimmerru** [comment]
Nice, thanks for quick responses. In this case i see no reasons to keep the issue opened.

**Comment by vimmerru** [comment]
@mcarrickscott See https://help.github.com/articles/creating-releases/ it explains how to create releases from GH UI
